"""Add indexes and unique constraint to aqi_data — production-safe migration.

This migration ONLY modifies the ``aqi_data`` table. It does NOT drop any
other tables. The original autogenerated migration (generated from a
development database containing legacy tables) incorrectly included DROP
statements for ``user_notification_preferences``, ``predictions``,
``weather_data``, ``user_city_subscriptions``, ``locations``,
``measurements``, and ``air_quality_data``.  Those tables are NOT part of
the current ORM and must not be dropped — they may contain live data or
be used by other systems.

Revision ID: f3a1b2c4d5e6
Revises:
Create Date: 2026-07-15

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3a1b2c4d5e6'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add indexes and unique constraint to aqi_data.

    SAFE on existing production databases:
    * Duplicate ``(location_name, recorded_at)`` pairs are deduplicated
      BEFORE the unique constraint is applied using a DELETE that keeps
      the row with the lowest ``id``.
    * Indexes are created with ``IF NOT EXISTS`` (via Alembic's
      ``checkfirst=True``) so re-running the migration is idempotent.
    * No other tables are modified.
    """
    conn = op.get_bind()

    # ── Step 1: Deduplicate existing rows BEFORE adding the unique constraint ──
    # Identify and remove duplicate (location_name, recorded_at) pairs,
    # keeping the row with the lowest id (earliest insert).
    # This prevents "could not create unique index" on existing data.
    conn.execute(sa.text("""
        DELETE FROM aqi_data
        WHERE id IN (
            SELECT id FROM (
                SELECT id,
                       ROW_NUMBER() OVER (
                           PARTITION BY location_name, recorded_at
                           ORDER BY id
                       ) AS rn
                FROM aqi_data
                WHERE location_name IS NOT NULL
                  AND recorded_at IS NOT NULL
            ) sub
            WHERE rn > 1
        )
    """))

    # ── Step 2: Drop old index if it exists (was named differently) ──────────
    # The previous expression index used a different name; drop it so we can
    # create the correctly-named replacement below.
    op.execute(
        "DROP INDEX IF EXISTS idx_aqi_data_lower_city_recorded_at"
    )

    # ── Step 3: Create replacement indexes ───────────────────────────────────
    op.create_index(
        'ix_aqi_data_city_recorded_at',
        'aqi_data',
        ['city', 'recorded_at'],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        'ix_aqi_data_location_name',
        'aqi_data',
        ['location_name'],
        unique=False,
        if_not_exists=True,
    )

    # ── Step 4: Add unique constraint ────────────────────────────────────────
    # Runs only if the constraint does not already exist.
    result = conn.execute(sa.text("""
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'uq_aqi_data_location_recorded_at'
          AND table_name = 'aqi_data'
    """)).fetchone()
    if not result:
        op.create_unique_constraint(
            'uq_aqi_data_location_recorded_at',
            'aqi_data',
            ['location_name', 'recorded_at'],
        )


def downgrade() -> None:
    """Remove the unique constraint and indexes added in upgrade()."""
    op.drop_constraint(
        'uq_aqi_data_location_recorded_at', 'aqi_data', type_='unique'
    )
    op.drop_index('ix_aqi_data_location_name', table_name='aqi_data')
    op.drop_index('ix_aqi_data_city_recorded_at', table_name='aqi_data')
